jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Replace API Key in info.json
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
        run: |
          jq '.api_endpoints.token_holder_list |= sub("YOUR_API_KEY"; env.BSCSCAN_API_KEY) |
                .api_endpoints.contract_creation |= sub("YOUR_API_KEY"; env.BSCSCAN_API_KEY) |
                .api_endpoints.source_code |= sub("YOUR_API_KEY"; env.BSCSCAN_API_KEY)' info.json > temp.json && mv temp.json info.json
